# recall to run this every time you update:
# "C:\Users\alfon\hugo\hugo.exe" -d docs
# git add .
# git commit -m "Update site"
# git push origin main

baseURL: "https://alfonsomerendino.github.io/"
languageCode: "en-us"
title: "Alfonso Merendino"
theme: "PaperMod"

enableRobotsTXT: true

pagination:
  pagerSize: 10

taxonomies:
  tag: "tags"
  category: "categories"

# --- PaperMod / template options ---
params:
  author: "Alfonso Merendino"
  description: ""
  defaultTheme: "light"
  disableThemeToggle: true
  dateFormat: "Jan 2, 2006"
  hideFooter: false          # no footer text, like the template

  # --- Homepage profile block (center card) ---
  profileMode:
    enabled: true
    title: "Alfonso Merendino"
    subtitle: "Hi! I am an incoming PhD student in Economics at **[Yale](https://economics.yale.edu/)**, a trainee at the **[European Central Bank](https://www.ecb.europa.eu/home/html/index.en.html)** and a Research Fellow at the **[Social Economics Lab](https://socialeconomicslab.org/)**. I received both my Bachelor’s and my Master’s in Economics from **[Bocconi](https://www.unibocconi.it/en)**. I am interested in macroeconomics and trade."
    imageUrl: "profilepicture_v2.jpg"
    imageTitle: "Alfonso Merendino"
    buttons:
      - name: "Work in progress"
        url: "/work-in-progress/"

#      - name: "Policy articles"
#        url: "/policy-articles/"
  # social icons under the profile
  socialIcons:
    - name: "Email"
      url: "mailto:alfonso.merendino@ecb.europa.eu"
    - name: "Linkedin"
      url: "https://www.linkedin.com/in/alfonso-merendino-95b055151/?originalSubdomain=it"

#    - name: "CV"
#      url: "/cv.pdf"                          # place cv.pdf in the static/ folder

  # misc PaperMod flags
  ShowShareButtons: false
  ShowReadingTime: false
  showtoc: false
  env: "production"


